### ISSUE TITLE
编译好之后，麻烦分享一下固件

### ISSUE THREAD

**Issue by choicky** [wangfeng35/OpenWrt-MT7621-Redmi-AC2100#1]
如题。

btw，我目前也复制了一份你的.config 去编译，明天看看编译结果。

**Comment by wangfeng35** [comment]
> 如题。
> 
> btw，我目前也复制了一份你的.config 去编译，明天看看编译结果。

编译失败了 我也不懂为什么 还是去恩山上找现成的了
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=4019555

**Comment by choicky** [comment]
我年初给我的x86软路由编译过一次，成功了，当时还把 .config 备份了。现在重新编就没成功过。不知是不是因为我从ubuntu 18.04升级到20.04

ac2100的固件，我更是没成功过

**Comment by wangfeng35** [comment]
> 我年初给我的x86软路由编译过一次，成功了，当时还把 .config 备份了。现在重新编就没成功过。不知是不是因为我从ubuntu 18.04升级到20.04
> 
> ac2100的固件，我更是没成功过

所以直接用恩山大佬的了 不折腾了 哈哈

**Comment by wangfeng35** [comment]
> 我年初给我的x86软路由编译过一次，成功了，当时还把 .config 备份了。现在重新编就没成功过。不知是不是因为我从ubuntu 18.04升级到20.04
> 
> ac2100的固件，我更是没成功过

最新版成功了，还没测试可用性：https://github.com/wangfeng35/OpenWrt-MT7621-Redmi-AC2100/actions
